import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  mainview: {backgroundColor: '#fff', marginVertical: 20, padding: 20},
  dpView: {
    height: 30,
    marginTop: 25,
    marginLeft: 20,
    width: 30,
    position: 'absolute',
  },
  nameView: {
    fontSize: 16,
    color: 'black',
    paddingLeft: 35,
  },
  timeView: {
    color: '#100B0066',
    paddingLeft: 35,
    paddingBottom: 5,
    fontSize: 14,
  },
  heartView: {
    height: 30,
    marginTop: 25,
    width: 30,
    right: 30,
    position: 'absolute',
  },
  swiperView: {height: 180, marginTop: 10, width: 345},
  swiperImg: {height: 180, width: 345, borderRadius: 2},
  descView: {marginTop: 30, fontSize: 16, lineHeight: 25, color: '#100B0066'},
  lineView: {
    margin: 5,
    marginVertical: 20,
    flex: 1,
    height: 1.5,
    backgroundColor: '#1A110033',
  },
  iconsView: {
    flexDirection: 'row',
    marginHorizontal: 30,
    justifyContent: 'space-between',
  },
  likeImg: {height: 20, width: 22},
  likeCount: {color: '#100B0066', marginLeft: 5},
  commentImg: {height: 20, width: 22},
  commentCount: {color: '#100B0066', marginLeft: 5},
  shareImg: {height: 20, width: 22},
  shareCount: {
    color: '#100B0066',
    marginLeft: 5,
  },
  commentView: {
    marginTop: 20,
    flexDirection: 'row',
  },
  commentInput: {
    borderColor: 'grey',
    width: '88%',
    marginLeft: 10,
    color: '#100B0099',
    borderWidth: 0.5,
    borderColor: 'grey',
  },
  commentCount: {color: 'grey'},
  comment2ndCount: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 10,
  },
  secLine: {
    height: '100%',
    width: 1,
    backgroundColor: '#1A110033',
    position: 'absolute',
  },
  commentInsideView: {paddingLeft: 10, paddingTop: 5},
  commentText: {
    marginTop: 10,
    fontSize: 16,
    lineHeight: 20,
    color: '#100B0066',
  },
  loadMore: {color: 'black', marginTop: 10},
  commentDp: {
    height: 30,
    marginTop: 12,
    width: 30,
  },
  dpactiveImg: {height: 30, marginTop: 10, width: 30},
  commentboxView: {marginTop: 20, flexDirection: 'row'},
  commentName: {fontSize: 16, color: 'black'},
  commentTime: {
    color: '#100B0066',
    paddingBottom: 5,
    fontSize: 14,
  },
});
